### ISSUE TITLE
v2.0 TODO

### ISSUE THREAD

**Issue by nange** [nange/easyss#15]
- [x] easyss-server 命令行删除Method, Timeout配置项；
- [x] 系统托盘菜单重构为：
```text
选择配置
代理规则:
    自动(绕过大陆IP域名+自定义配置)
    全局连接
    直接连接
代理对象：
    浏览器(设置系统代理)
    系统全局流量(Tun2socks)
查看运行日志
退出
```
- [x] bug：命令行指定了enable-tun2socks，切换配置后，托盘菜单没有选中
- [x] 命令行添加参数: proxy-rule: auto, proxy, direct
- [x] 代理浏览器实现: 删除PAC，改为Sysproxy库
- [x] 重构切换配置功能，改为切换服务器，统一成一个配置文件，server改为数组，需重新设计配置文件格式
- [x] 服务启动时，查询服务器DNS，支持DNS服务器列表：腾讯云、阿里云、百度云。

**Comment by nange** [comment]
ALL DONE！

**Comment by nange** [comment]
Add a new issue:
- [ ] 在Mac上，不设置DNS，用默认的，无法访问外网：DNS请求没有进入easy，查询出的dns结果不对造成

**Comment by nange** [comment]
- [ ] 日志格式重构
- [ ] 优先使用waitgroup等待多goroutine后台完成
- [ ] easy 后台goroutine，检测dns服务器可用性，如不可用则尝试其他的并修改
- [ ] TCP relay 一方断掉后，不要直接关闭另一方的连接，通过设置一个read dead time时间，等待对方完成。这样才符合tcp规范。直连场景和代理场景，都需考虑
- [ ] 添加github Action，完成基本的vet，lint

**Comment by nange** [comment]
- [ ] 支持自定义证书
- [ ] 添加NewEasyssServer方法，只做服务端需要的初始化，不要做多余的操作
- [ ] 优化relay代码

**Comment by nange** [comment]
All Done! Will release v2.0 soon.
